### PR TITLE
Migrate some easy components to ES6

### PR DESCRIPTION
**Pull request by Stampede10343**
**Changes**

Converted `filedownloader.js`, `filesystem.js`, `keyboardnavigation.js`, and `sanitizefilename.js` to ES6.

**Issues**

Part of #868

### CODE REVIEW

**Comment by dkanada** [comment]
I mentioned this to @MrTimscampi earlier but we should leave whitespace alone during the transition and simply disable the linting like he did in his pull request to make diffs painless to review.

**Comment by Stampede10343** [comment]
> I mentioned this to @MrTimscampi earlier but we should leave whitespace alone during the transition and simply disable the linting like he did in his pull request to make diffs painless to review.

Ah so should we not do any conversion of `var`'s to `const` or anything like that? Just to limit noise for the large group of files.

**Comment by MrTimscampi** [comment]
> > I mentioned this to @MrTimscampi earlier but we should leave whitespace alone during the transition and simply disable the linting like he did in his pull request to make diffs painless to review.
> 
> Ah so should we not do any conversion of `var`'s to `const` or anything like that? Just to limit noise for the large group of files.

That you can :) JSDoc is also encouraged if you have the time/patience to do it (it's really boring to do), but not necessary (The priority is getting rid of AMD).
But keep the wonky indentation for everything except the imports.

That way it's easier for us to review. You can look at the ES6 pull request for pointers (Specifically the very first line that disabled the ESLint for indent in the file).

**Comment by dkanada** [comment]
@Stampede10343 it would also probably be better if you opened these pull requests against the official repository so @MrTimscampi doesn't have to handle the final merge.

**Comment by Stampede10343** [comment]
> @Stampede10343 it would also probably be better if you opened these pull requests against the official repository so @MrTimscampi doesn't have to handle the final merge.

Ah I just figured since I branched off his branch it would be easier to tell what changed. But I'm up for whatever works best.

**Comment by MrTimscampi** [comment]
@Stampede10343 The initial merge for the ES6 move is done. Could you rebase your change on the master and open a PR on the main jellyfin-repo, please ? Thanks.

**Pull request closed without merging**
